// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGB-zTUFHyufsPDOKr1ija1MdpQwypgwI',
    appId: '1:97657481061:web:a69f7a04764795ff0ca38c',
    messagingSenderId: '97657481061',
    projectId: 'testproject1-e4cfb',
    authDomain: 'testproject1-e4cfb.firebaseapp.com',
    storageBucket: 'testproject1-e4cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAQNW0mcN-0K9CzoEcSBeCIEPYlxJ0ZU',
    appId: '1:97657481061:android:554c3269037eb1ba0ca38c',
    messagingSenderId: '97657481061',
    projectId: 'testproject1-e4cfb',
    storageBucket: 'testproject1-e4cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBFkJsBQ2BS1nvq-rfIGbkU0I4Qp881w',
    appId: '1:97657481061:ios:bbe3623680f5a7c70ca38c',
    messagingSenderId: '97657481061',
    projectId: 'testproject1-e4cfb',
    storageBucket: 'testproject1-e4cfb.firebasestorage.app',
    iosBundleId: 'com.example.testscanner1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGB-zTUFHyufsPDOKr1ija1MdpQwypgwI',
    appId: '1:97657481061:web:216b8837e997ca9d0ca38c',
    messagingSenderId: '97657481061',
    projectId: 'testproject1-e4cfb',
    authDomain: 'testproject1-e4cfb.firebaseapp.com',
    storageBucket: 'testproject1-e4cfb.firebasestorage.app',
  );
}
